=== mindcrime/jcolibri/xml/methods.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Juanan (ucm) -->
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by Nasdaq Boom (World of Cracking) -->
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Methods">
		<xs:annotation>
			<xs:documentation>Available methods on the system, associated with the solved task</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Method" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Method">
		<xs:annotation>
			<xs:documentation>Method declaration</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" type="xs:string"/>
				<xs:element name="Description" type="xs:string"/>
				<xs:element ref="ContextInputPrecondition" minOccurs="0"/>
				<xs:element ref="Type"/>
				<xs:element ref="Parameters" minOccurs="0"/>
				<xs:element ref="Competencies"/>
				<xs:element ref="SubTasks" minOccurs="0"/>
				<xs:element ref="ContextOutputPostcondition" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Type">
		<xs:annotation>
			<xs:documentation>Methods could be of type resolution or decomposition, depending if they solve the task or just decompose it in more tasks</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Decomposition"/>
				<xs:enumeration value="Resolution"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Parameters">
		<xs:annotation>
			<xs:documentation>Parameters set on the method instantation</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Parameter" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Parameter" type="ParameterType"/>
	<xs:element name="Competencies">
		<xs:annotation>
			<xs:documentation>List of tasks that this method is able to solve</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Competence" type="xs:string" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SubTasks">
		<xs:annotation>
			<xs:documentation>On decomposition type methods is the list of subtasks on which the main task is devided</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SubTask" type="xs:string" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ContextCondition" type="ContextConditionType">
		<xs:annotation>
			<xs:documentation>Occurences and type of the data that is on the context</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="ContextInputPrecondition">
		<xs:annotation>
			<xs:documentation>Preconditions related to the context for this method execution</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ContextCondition" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ContextOutputPostcondition">
		<xs:annotation>
			<xs:documentation>Postconditions related to the context once the method is executed</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ContextCondition" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ParameterType">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="Description" type="xs:string" minOccurs="0"/>
			<xs:choice>
				<xs:element name="DataType" type="DataTypeType"/>
				<xs:element name="CBRTerm" type="CBRTermType">
					<xs:annotation>
						<xs:documentation>References to JColibri objects: CBRCase, CBRCaseSim, ...</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ContextConditionType">
		<xs:choice>
			<xs:sequence>
				<xs:element name="MaxOccurrences" type="OccurrenceType"/>
				<xs:element name="MinOccurrences" type="OccurrenceType"/>
				<xs:element name="CBRTerm" type="CBRTermType">
					<xs:annotation>
						<xs:documentation>References to JColibri objects: CBRCase, CBRCaseSim, ...</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:sequence>
				<xs:element ref="Parameter"/>
			</xs:sequence>
		</xs:choice>
	</xs:complexType>
	<xs:simpleType name="OccurrenceType">
		<xs:annotation>
			<xs:documentation>Declares the number of requiered entities: undefined or any number</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="\p{N}|undefined"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CBRTermType">
		<xs:annotation>
			<xs:documentation>References to JColibri objects: CBRCase, CBRCaseSim, ...</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="DataTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="String"/>
			<xs:enumeration value="Boolean"/>
			<xs:enumeration value="Double"/>
			<xs:enumeration value="Integer"/>
			<xs:enumeration value="Date"/>
			<xs:enumeration value="Object"/>
			<xs:enumeration value="File"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== mindcrime/jcolibri/config/web/methods.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Methods xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\xml\methods.xsd">


	<Method>
		<Name>jcolibri.extensions.web.method.WebPreCycleMethod</Name>
		<Description>Pre cycle method that launches the web server and loads the case base</Description>
		<Type>Decomposition</Type>
		<Competencies>
			<Competence>PreCycle</Competence>
		</Competencies>
		<SubTasks>
			<SubTask>Start Web Server task</SubTask>
			<SubTask>Obtain cases task</SubTask>
		</SubTasks>
	</Method>

	<Method>
		<Name>jcolibri.extensions.web.method.WebPostCycleMethod</Name>
		<Description>Post cycle method that stops the web server and stores the case base</Description>
		<Type>Decomposition</Type>
		<Competencies>
			<Competence>PostCycle</Competence>
		</Competencies>
		<SubTasks>
			<SubTask>Stop Web Server task</SubTask>
			<SubTask>Close connector task</SubTask>
		</SubTasks>
	</Method>



	<Method>
		<Name>jcolibri.extensions.web.method.StartTomcatMethod</Name>
		<Description>Starts Tomcat web server</Description>
		<Type>Resolution</Type>
		<Competencies>
			<Competence>Start Web Server task</Competence>
		</Competencies>
	</Method>


	<Method>
		<Name>jcolibri.extensions.web.method.StopTomcatMethod</Name>
		<Description>Starts Tomcat web server</Description>
		<Type>Resolution</Type>
		<Competencies>
			<Competence>Stop Web Server task</Competence>
		</Competencies>
	</Method>

	<Method>
		<Name>jcolibri.extensions.web.method.ObtainWebQueryMethod</Name>
		<Description>Obtains the query from the web server</Description>
		<Type>Resolution</Type>
		<Parameters>
			<Parameter>
				<Name>Case Structure</Name>
				<Description>XML file generated by jCOLIBRI tools</Description>
				<DataType>File</DataType>
			</Parameter>
			<Parameter>
				<Name>Time out</Name>
				<Description>Maximum time that cycle waits for the query</Description>
				<DataType>Integer</DataType>
			</Parameter>
		</Parameters>
		<Competencies>
			<Competence>Obtain query task</Competence>
		</Competencies>
	</Method>
	
	<Method>
		<Name>jcolibri.extensions.web.method.CBRWebMethod</Name>
		<Description>Main CBR method that will divide CBR process in the four typical tasks and some extra tasks for cycle synchronization with the web server</Description>
		<Type>Decomposition</Type>
		<Competencies>
			<Competence>CBR Cycle</Competence>
		</Competencies>
		<SubTasks>
			<SubTask>Start Web Cycle task</SubTask>
			<SubTask>Obtain query task</SubTask>
			<SubTask>Retrieve Task</SubTask>
			<SubTask>Reuse Task</SubTask>
			<SubTask>Revise Task</SubTask>
			<SubTask>Retain Task</SubTask>
			<SubTask>Stop Web Cycle task</SubTask>
		</SubTasks>
	</Method>

	<Method>
		<Name>jcolibri.extensions.web.method.StartWebCycleMethod</Name>
		<Description>Starts the web CBR cycle</Description>
		<Type>Resolution</Type>
		<Competencies>
			<Competence>Start Web Cycle task</Competence>
		</Competencies>
	</Method>
	
	<Method>
		<Name>jcolibri.extensions.web.method.StopWebCycleMethod</Name>
		<Description>Stops the web CBR cycle</Description>
		<Type>Resolution</Type>
		<Competencies>
			<Competence>Stop Web Cycle task</Competence>
		</Competencies>
	</Method>

	<Method>
		<Name>jcolibri.extensions.web.method.RetrieveComputationalForWebServerMethod</Name>
		<Description>Simple retrieve strategy that sends the cases to the Web Server</Description>
		<Type>Decomposition</Type>
		<Competencies>
			<Competence>Retrieve Task</Competence>
		</Competencies>
		<SubTasks>
			<SubTask>Select working cases task</SubTask>
			<SubTask>Compute similarity task</SubTask>
			<SubTask>Select best task</SubTask>
			<SubTask>Send Cases to Web Server task</SubTask>
		</SubTasks>
	</Method>

	
	<Method>
		<Name>jcolibri.extensions.web.method.SendCasesToWebServerMethod</Name>
		<Description>Sends retrieved cases to the Web Server</Description>
		<Type>Resolution</Type>
		<Competencies>
			<Competence>Send Cases to Web Server task</Competence>
		</Competencies>
	</Method>


</Methods>

=== mindcrime/jcolibri/config/DL/methods.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Methods xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\xml\methods.xsd">
	<Method>
		<Name>jcolibri.extensions.DL.method.LoadDLCaseBaseMethod</Name>
		<Description>Loads the Case Base from a DLs Reasoner</Description>
		<Type>Resolution</Type>
		<Parameters>
			<Parameter>
				<Name>Case Structure</Name>
				<Description>Case Structure configuration file</Description>
				<DataType>File</DataType>
			</Parameter>
		</Parameters>
		<Competencies>
			<Competence>Obtain cases task</Competence>
		</Competencies>
	</Method>
	<Method>
		<Name>jcolibri.extensions.DL.method.ConfigureDLQueryMethod</Name>
		<Description>Asks user for the DL query using the XML file generated by jCOLIBRI tools. It also configures similarity functions.</Description>
		<Type>Resolution</Type>
		<Parameters>
			<Parameter>
				<Name>Case Structure</Name>
				<Description>XML file generated by jCOLIBRI tools</Description>
				<DataType>File</DataType>
			</Parameter>
		</Parameters>
		<Competencies>
			<Competence>Obtain query task</Competence>
		</Competencies>
	</Method>
	
	<Method>
		<Name>jcolibri.extensions.DL.method.DLAdaptationMethod</Name>
		<Description>Performs several adaptations defined by rules</Description>
		<Type>Resolution</Type>
		<Parameters>
			<Parameter>
				<Name>Rules file</Name>
				<Description>Adapatation rules file</Description>
				<DataType>File</DataType>
			</Parameter>
			<Parameter>
				<Name>Solution Attribute</Name>
				<Description>Attribute of the solution that contains the concept type value that links with the instance to adapt</Description>
				<DataType>String</DataType>
			</Parameter>
		</Parameters>
		<Competencies>
			<Competence>Atomic Reuse Task</Competence>
		</Competencies>
	</Method>
</Methods>

=== mindcrime/jcolibri/config/core/methods.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Methods xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\xml\methods.xsd">
	<Method>
		<Name>jcolibri.method.LoadCaseBaseMethod</Name>
		<Description>Loads the Case Base from the persistence layer, using a connector configured in a xml file</Description>
		<Type>Resolution</Type>
		<Parameters>
			<Parameter>
				<Name>Connector</Name>
				<Description>Connector configuration file</Description>
				<DataType>File</DataType>
			</Parameter>
		</Parameters>
		<Competencies>
			<Competence>Obtain cases task</Competence>
		</Competencies>
	</Method>
	<Method>
		<Name>jcolibri.method.SelectBestCaseMethod</Name>
		<Description>Selects just the best of the found cases</Description>
		<Type>Resolution</Type>
		<Competencies>
			<Competence>Select best task</Competence>
		</Competencies>
	</Method>
	<Method>
		<Name>jcolibri.method.RetrieveComputationalMethod</Name>
		<Description>Simple retrieve strategy</Description>
		<Type>Decomposition</Type>
		<Competencies>
			<Competence>Retrieve Task</Competence>
		</Competencies>
		<SubTasks>
			<SubTask>Select working cases task</SubTask>
			<SubTask>Compute similarity task</SubTask>
			<SubTask>Select best task</SubTask>
		</SubTasks>
	</Method>
	<Method>
		<Name>jcolibri.method.CBRSystemMethod</Name>
		<Description>Divides our CBR system into precycle/cycle/postcycle</Description>
		<Type>Decomposition</Type>
		<Competencies>
			<Competence>CBR System</Competence>
		</Competencies>
		<SubTasks>
			<SubTask>PreCycle</SubTask>
			<SubTask>CBR Cycle</SubTask>
			<SubTask>PostCycle</SubTask>
		</SubTasks>
	</Method>

	<Method>
		<Name>jcolibri.method.PreCycleMethod</Name>
		<Description>Standard pre cycle method</Description>
		<Type>Decomposition</Type>
		<Competencies>
			<Competence>PreCycle</Competence>
		</Competencies>
		<SubTasks>
			<SubTask>Obtain cases task</SubTask>
		</SubTasks>
	</Method>

	<Method>
		<Name>jcolibri.method.PostCycleMethod</Name>
		<Description>Standard post cycle method</Description>
		<Type>Decomposition</Type>
		<Competencies>
			<Competence>PostCycle</Competence>
		</Competencies>
		<SubTasks>
			<SubTask>Close connector task</SubTask>
		</SubTasks>
	</Method>

	
	
	<Method>
		<Name>jcolibri.method.CloseConnectorMethod</Name>
		<Description>Closes the case base releasing connector resources</Description>
		<Type>Resolution</Type>
		<Competencies>
			<Competence>Close connector task</Competence>
		</Competencies>
	</Method>

	<Method>
		<Name>jcolibri.method.SelectAllCasesMethod</Name>
		<Description>Stores all cases as working cases</Description>
		<Type>Resolution</Type>
		<Competencies>
			<Competence>Select working cases task</Competence>
		</Competencies>
	</Method>
	
	<Method>
		<Name>jcolibri.method.CBRMethod</Name>
		<Description>Main CBR method that will divide CBR process in the four typical tasks.</Description>
		<Type>Decomposition</Type>
		<Competencies>
			<Competence>CBR Cycle</Competence>
		</Competencies>
		<SubTasks>
			<SubTask>Obtain query task</SubTask>
			<SubTask>Retrieve Task</SubTask>
			<SubTask>Reuse Task</SubTask>
			<SubTask>Revise Task</SubTask>
			<SubTask>Retain Task</SubTask>
		</SubTasks>
	</Method>
	<Method>
		<Name>jcolibri.method.NumericSimComputationMethod</Name>
		<Description>Applies simple numeric similarity measures to cases</Description>
		<Type>Resolution</Type>
		<Competencies>
			<Competence>Compute similarity task</Competence>
		</Competencies>
	</Method>
	<Method>
		<Name>jcolibri.method.SelectSomeCasesMethod</Name>
		<Description>Select the cases indicated by user</Description>
		<Type>Resolution</Type>
		<Parameters>
			<Parameter>
				<Name>Number of cases</Name>
				<Description>Number of cases to be returned</Description>
				<DataType>Integer</DataType>
			</Parameter>
		</Parameters>
		<Competencies>
			<Competence>Select best task</Competence>
		</Competencies>
	</Method>
		<Method>
		<Name>jcolibri.method.ConfigureQueryMethod</Name>
		<Description>Asks user for the query using the XML file generated by jCOLIBRI tools. It also configures similarity functions.</Description>
		<Type>Resolution</Type>
		<Parameters>
			<Parameter>
				<Name>Case Structure</Name>
				<Description>XML file generated by jCOLIBRI tools</Description>
				<DataType>File</DataType>
			</Parameter>
		</Parameters>
		<Competencies>
			<Competence>Obtain query task</Competence>
		</Competencies>
	</Method>

	<Method>
		<Name>jcolibri.method.ReuseComputationalMethod</Name>
		<Description>Simple reuse strategy. Divides a reuse task into atomic reuse tasks and a main Reuse Task. This way, developers can apply several reuse methods.</Description>
		<Type>Decomposition</Type>
		<Competencies>
			<Competence>Reuse Task</Competence>
		</Competencies>
		<SubTasks>
			<SubTask>Prepare Cases for Adaptation Task</SubTask>
			<SubTask>Atomic Reuse Task</SubTask>
			<SubTask>Atomic Reuse Task</SubTask>
			<SubTask>Atomic Reuse Task</SubTask>
			<SubTask>Atomic Reuse Task</SubTask>
			<SubTask>Atomic Reuse Task</SubTask>
			<SubTask>Reuse Task</SubTask>
		</SubTasks>
	</Method>


<Method>
		<Name>jcolibri.method.CopyCasesforAdaptationMethod</Name>
		<Description>Removes evaluation data in retrieved cases.</Description>
		<Type>Resolution</Type>
		<Parameters>
			<Parameter>
				<Name>Case Structure</Name>
				<Description>XML file generated by jCOLIBRI tools</Description>
				<DataType>File</DataType>
			</Parameter>
		</Parameters>
		<Competencies>
			<Competence>Prepare Cases for Adaptation Task</Competence>
		</Competencies>
</Method>



<Method>
		<Name>jcolibri.method.CombineQueryAndCasesMethod</Name>
		<Description>Copies Query description into retrieved cases</Description>
		<Type>Resolution</Type>
		<Competencies>
			<Competence>Atomic Reuse Task</Competence>
		</Competencies>
</Method>

<Method>
		<Name>jcolibri.method.DirectCopyMethod</Name>
		<Description>Copies a Description attribute value to a solution attribute</Description>
		<Type>Resolution</Type>
		<Parameters>
			<Parameter>
				<Name>Description Attribute</Name>
				<Description>Attribute from Description to be copied</Description>
				<DataType>String</DataType>
			</Parameter>
			<Parameter>
				<Name>Solution Attribute</Name>
				<Description>Attribute from Solution where value must be stored</Description>
				<DataType>String</DataType>
			</Parameter>
		</Parameters>
		<Competencies>
			<Competence>Atomic Reuse Task</Competence>
		</Competencies>
	</Method>

<Method>
		<Name>jcolibri.method.NumericDirectProportionMethod</Name>
		<Description>Computes a direct proportion between NUMERIC description attributes and solution attributes.</Description>
		<Type>Resolution</Type>
		<Parameters>
			<Parameter>
				<Name>Description Attribute</Name>
				<Description>Attribute from Description that indicates the proportion</Description>
				<DataType>String</DataType>
			</Parameter>
			<Parameter>
				<Name>Solution Attribute</Name>
				<Description>Attribute from Solution where proportion must be stored</Description>
				<DataType>String</DataType>
			</Parameter>
		</Parameters>
		<Competencies>
			<Competence>Atomic Reuse Task</Competence>
		</Competencies>
</Method>

		<Method>
		<Name>jcolibri.method.ManualRevisionMethod</Name>
		<Description>Allows user to modify cases</Description>
		<Type>Resolution</Type>
		<Parameters>
			<Parameter>
				<Name>Case Structure</Name>
				<Description>XML file generated by jCOLIBRI tools</Description>
				<DataType>File</DataType>
			</Parameter>
		</Parameters>
		<Competencies>
			<Competence>Revise Task</Competence>
		</Competencies>
	</Method>


	<Method>
		<Name>jcolibri.method.RetainComputationalMethod</Name>
		<Description>Simple retain strategy</Description>
		<Type>Decomposition</Type>
		<Competencies>
			<Competence>Retain Task</Competence>
		</Competencies>
		<SubTasks>
			<SubTask>Select cases to store task</SubTask>
			<SubTask>Store cases task</SubTask>
		</SubTasks>
	</Method>
	<Method>
		<Name>jcolibri.method.RetainChooserMethod</Name>
		<Description>Allows user to choose cases to store</Description>
		<Type>Resolution</Type>
		<Parameters>
			<Parameter>
				<Name>Case Structure</Name>
				<Description>XML file generated by jCOLIBRI tools</Description>
				<DataType>File</DataType>
			</Parameter>
		</Parameters>
		<Competencies>
			<Competence>Select cases to store task</Competence>
		</Competencies>
	</Method>
	
	<Method>
		<Name>jcolibri.method.StoreCasesMethod</Name>
		<Description>Stores cases into CaseBase</Description>
		<Type>Resolution</Type>
		<Competencies>
			<Competence>Store cases task</Competence>
		</Competencies>
	</Method>

</Methods>
